[project]
name = "pyhamlogger"
version = "0.1.0"
description = "PyHamLogger is an open-source Python-based GUI application designed for logging ham radio contacts."
authors = [{ name = "Bobby Warren", email = "blwarren@gmail.com" }]
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "pyqt6>=6.7.1,<7.0.0",
    "pydantic>=2.8.2,<3.0.0",
]

[project.scripts]
pyhamlogger = "pyhamlogger.main:main"

[dependency-groups]
dev = [
    "pytest>=8.3.2,<9.0.0",
    "pytest-qt>=4.4.0,<5.0.0",
]

[tool.ruff]
line-length = 100

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = ""
source-exclude = ["pyhamlogger/data/**"]
wheel-exclude = ["pyhamlogger/data/**"]
